export const FILTER_SOURCE = {
  ALL: 'ALL',
  CBRE: 'CBRE',
  TEAM: 'TEAM'
};

export const CELL_TYPE = {
  VALUE: 'VALUE',
  NAME_ADDRESS: 'NAME_ADDRESS',
  MIN_MAX: 'MIN_MAX',
  SELECT_ROW: 'SELECT_ROW',
  SOURCE: 'SOURCE',
  PHOTO: 'PHOTO'
};